CREATE TABLE food
(
    food_id          BIGINT NOT NULL,
    food_name        VARCHAR(255),
    food_description VARCHAR(255),
    food_price       DOUBLE PRECISION,
    food_restaurant  BIGINT,
    CONSTRAINT pk_food PRIMARY KEY (food_id)
);

CREATE TABLE "order"
(
    order_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_user        BIGINT,
    order_restaurant  BIGINT,
    order_total_price DOUBLE PRECISION,
    order_status      SMALLINT,
    CONSTRAINT pk_order PRIMARY KEY (order_id)
);

CREATE TABLE order_food
(
    food_id  BIGINT NOT NULL,
    order_id BIGINT NOT NULL
);

CREATE TABLE restaurant
(
    restaurant_id      BIGINT NOT NULL,
    restaurant_name    VARCHAR(255),
    restaurant_address VARCHAR(255),
    CONSTRAINT pk_restaurant PRIMARY KEY (restaurant_id)
);

CREATE TABLE "user"
(
    user_id       BIGINT NOT NULL,
    user_name     VARCHAR(255),
    user_email    VARCHAR(255),
    user_password VARCHAR(255),
    user_type     SMALLINT,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

ALTER TABLE restaurant
    ADD CONSTRAINT uc_restaurant_restaurant_name UNIQUE (restaurant_name);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_user_email UNIQUE (user_email);

ALTER TABLE food
    ADD CONSTRAINT FK_FOOD_ON_FOOD_RESTAURANT FOREIGN KEY (food_restaurant) REFERENCES restaurant (restaurant_id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_ORDER_RESTAURANT FOREIGN KEY (order_restaurant) REFERENCES restaurant (restaurant_id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_ORDER_USER FOREIGN KEY (order_user) REFERENCES "user" (user_id);

ALTER TABLE order_food
    ADD CONSTRAINT fk_ordfoo_on_food FOREIGN KEY (food_id) REFERENCES food (food_id);

ALTER TABLE order_food
    ADD CONSTRAINT fk_ordfoo_on_order FOREIGN KEY (order_id) REFERENCES "order" (order_id);